name: Java CI with Maven - Test and package

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'coretto'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml